name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "partytimeapp"
          heroku_email: "kitebook.surf@gmail.com"
          usedocker: true
          docker_build_args: |
            username
            password
            url
        env:
          url: ${{ secrets.DB_URL}}
          username: ${{ secrets.DB_USERNAME}}
          password: ${{ secrets.DB_PASSWORD}}
