name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DB_URL: ${{ secrets.DB_URL}}
        DB_USERNAME: ${{ secrets.DB_USERNAME}}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --build-arg url=$DB_URL --build-arg username=$DB_USERNAME --build-arg dbpassword=$DB_PASSWORD

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "partytimeapp"
          heroku_email: "kitebook.surf@gmail.com"
          usedocker: true
          docker_build_args: |
            username
            dbpassword
            url
        env:
          url: ${{ secrets.DB_URL}}
          username: ${{ secrets.DB_USERNAME}}
          dbpassword: ${{ secrets.DB_PASSWORD}}
